version: "3.8"
services:
  server: 
    image: url-shortner:debug
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile 
      target: debug
    ports:
      - 8080:8080
      - 40000:40000
    volumes:
      - .:/go/app
    security_opt: 
      - seccomp:unconfined